# Generated by Django 5.0.7 on 2024-08-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_image_filter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default="../default_post_qywub8", upload_to="images/"
            ),
        ),
    ]
